# --------------------- #
#   Basic Information   #
# --------------------- #
remote_theme: daattali/beautiful-jekyll The theme you chose. You can change it to others like jekyll-theme-cayman.
title: Kaiyue Feng - Personal Homepage # Your website's title
author: Kaiyue Feng
description: > # A short bio that appears in search results and under your site title.
  Senior Undergraduate in Computer Science at NYU Shanghai
  My research interests include AI4Science, Reasoning and multimodal LLMs.
  Welcome to my personal website.
avatar: assets/photo.jpgs
# --------------------- #
#    Navigation Bar     #
# --------------------- #
# Most themes will use this list to build a navigation menu.
navigation:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: Publications
    url: /publications
  - title: CV
    url: /assets/pdf/CV.pdf # A direct link to your CV PDF file.

# --------------------- #
#     Social Links      #
# --------------------- #
# The format may vary by theme, but this is a common setup.
github_username: Bloominglightray
linkedin_website: https://www.linkedin.com/in/kaiyue-feng-4480622b8/
# google_scholar_id: [Your-Google-Scholar-ID]
# twitter_username: [Your-Academic-Twitter-Username]

# --------------------- #
#     Customization     #
# --------------------- #
# The following settings are optional.
# You can customize the theme by changing these values.
# For more details, please refer to the theme's documentation.