# --------------------- #
#   Basic Information   #
# --------------------- #
remote_theme: daattali/beautiful-jekyll
title: Kaiyue Feng - Personal Homepage
author: Kaiyue Feng
description: > # A short bio that appears in search results and under your site title.
  Senior Undergraduate in Computer Science at NYU Shanghai
  My research interests include AI4Science, Reasoning and multimodal LLMs.
  Welcome to my personal website.
avatar: assets/photo.jpg
email: your-email@example.com
location: Shanghai, China
url: https://bloominglightray.github.io
baseurl: ""
# --------------------- #
#    Navigation Bar     #
# --------------------- #
# Most themes will use this list to build a navigation menu.
navigation:
  - title: Home
    url: /

# --------------------- #
#     Social Links      #
# --------------------- #
# The format may vary by theme, but this is a common setup.
github_username: Bloominglightray
linkedin_website: https://www.linkedin.com/in/kaiyue-feng-4480622b8/
# google_scholar_id: [Your-Google-Scholar-ID]
# twitter_username: [Your-Academic-Twitter-Username]

# --------------------- #
#     Customization     #
# --------------------- #
# The following settings are optional.
# You can customize the theme by changing these values.
# For more details, please refer to the theme's documentation.

# --------------------- #
#     Pagination       #
# --------------------- #
# Set to false to disable pagination and show all posts on homepage
paginate: false
paginate_path: "/page/:num/"

# --------------------- #
#     Theme Settings    #
# --------------------- #
# Beautiful Jekyll specific settings
show_avatar: true
show_social_links: true
show_description: true
show_related_posts: false
show_share_buttons: true
show_comments: false
show_tags: true
show_categories: true

